version: '3.6'

services:
  php:
    image: phpswoole/swoole:latest
    container_name: symfony_php
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://user:password@db:5432/symfony_db"
    ports:
      - "9501:9501"
    command: bin/console swoole:server:run

  db:
    image: postgres:16
    container_name: symfony_db
    restart: always
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
